//
// This file is part of InfoGrid(tm). You may not use this file except in
// compliance with the InfoGrid license. The InfoGrid license and important
// disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
// have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
// or you do not consent to all aspects of the license and the disclaimers,
// no license is granted; do not use this file.
// 
// For more information about InfoGrid go to http://infogrid.org/
//
// Copyright 1998-2008 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
// All rights reserved.
//

package org.infogrid.comm;

/**
 * An interface supported by Messages that need to keep track of invocations,
 * such as for Remote Procedure Calls. The request ID is generated by
 * the sender. The receiver takes the requested ID (if present) and
 * sets it as the response ID; the latter is what the sender looks for in
 * incoming messages as response.
 */
public interface CarriesInvocationId
{
    /**
     * Set the request ID.
     *
     * @param id the request ID
     */
    public void setRequestId(
            long id );
    
    /**
     * Obtain the request ID.
     *
     * @return the request ID
     */
    public long getRequestId();

    /**
     * Set the response ID.
     *
     * @param id the response ID
     */
    public void setResponseId(
            long id );
    
    /**
     * Obtain the response ID.
     *
     * @return the response ID
     */
    public long getResponseId();
}
