//
// This file is part of InfoGrid(tm). You may not use this file except in
// compliance with the InfoGrid license. The InfoGrid license and important
// disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
// have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
// or you do not consent to all aspects of the license and the disclaimers,
// no license is granted; do not use this file.
// 
// For more information about InfoGrid go to http://infogrid.org/
//
// Copyright 1998-2010 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
// All rights reserved.
//

package org.infogrid.module;

import java.util.EventObject;

/**
 * An event generated by a ModuleRegistry.
 */
public class ModuleRegistryEvent
        extends
            EventObject
{
    private static final long serialVersionUID = 1L; // helps with serialization

    /**
      * Construct one.
      *
      * @param registry the ModuleRegistry that generated the event
      * @param adv the ModuleAdvertisement to which this event relates
      */
    public ModuleRegistryEvent(
            ModuleRegistry      registry,
            ModuleAdvertisement adv )
    {
        super( registry );

        theModuleAdvertisement = adv;
    }

    /**
     * Obtain the ModuleAdvertisement to which this event relates.
     *
     * @return the ModuleAdvertisement to which this event relates
     */
    public ModuleAdvertisement getModuleAdvertisement()
    {
        return theModuleAdvertisement;
    }

    /**
     * The ModuleAdvertisement to which this event relates.
     */
    protected ModuleAdvertisement theModuleAdvertisement;
}
